#include "STD_TYPES.h"
#include <util/delay.h>

#include "DIO_interface.h"
#include "TIMER_interface.h"

#include "MAPPING.h"

#include "MOTOR_config.h"
#include "MOTOR_interface.h"
#include "MOTOR_private.h"


u8 MOTOR_u8DCRotate(u8 Copy_u8Direction)
{
	u8 Local_u8ErrorState = OK;

	if (Copy_u8Direction == MOTOR_CLK_WISE)
	{
		DIO_u8SetPinValue(MOTOR_DC_PORT,MOTOR_DC_PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(MOTOR_DC_PORT,MOTOR_DC_PIN1,DIO_u8PIN_HIGH);

	}

	else if(Copy_u8Direction == MOTOR_UNTI_CLK_WISE)
	{
		DIO_u8SetPinValue(MOTOR_DC_PORT,MOTOR_DC_PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(MOTOR_DC_PORT,MOTOR_DC_PIN2,DIO_u8PIN_HIGH);
	}

	else
	{
		Local_u8ErrorState = NOK;
	}
	return Local_u8ErrorState;
}

void MOTOR_voidDCStop(void)
{
	DIO_u8SetPinValue(MOTOR_DC_PORT,MOTOR_DC_PIN1,DIO_u8PIN_LOW);
	DIO_u8SetPinValue(MOTOR_DC_PORT,MOTOR_DC_PIN2,DIO_u8PIN_LOW);
}

u8 MOTOR_u8StepperRotate(u8 Copy_u8Direction)
{
	u8 Local_u8ErrorState = OK;

	if(Copy_u8Direction == MOTOR_CLK_WISE)
	{
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_PINK,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_BLUE,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_YELLOW,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_ORANGE,DIO_u8PIN_HIGH);
		_delay_ms(2);

		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_BLUE,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_PINK,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_YELLOW,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_ORANGE,DIO_u8PIN_HIGH);
		_delay_ms(2);

		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_ORANGE,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_BLUE,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_PINK,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_YELLOW,DIO_u8PIN_HIGH);
		_delay_ms(2);

		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_YELLOW,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_BLUE,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_PINK,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_ORANGE,DIO_u8PIN_HIGH);
		_delay_ms(2);
	}
	else if (Copy_u8Direction == MOTOR_UNTI_CLK_WISE)
	{

		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_BLUE,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_PINK,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_YELLOW,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_ORANGE,DIO_u8PIN_HIGH);
		_delay_ms(2);

		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_PINK,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_BLUE,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_YELLOW,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_ORANGE,DIO_u8PIN_HIGH);
		_delay_ms(2);

		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_YELLOW,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_BLUE,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_PINK,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_ORANGE,DIO_u8PIN_HIGH);
		_delay_ms(2);

		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_ORANGE,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_BLUE,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_PINK,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_YELLOW,DIO_u8PIN_HIGH);
		_delay_ms(2);
	}

	else
	{
		Local_u8ErrorState = NOK;
	}
	return Local_u8ErrorState;
}

u8 MOTOR_u8StepperRotateAngle(u16 Copy_u16Angle,u8 Copy_u8Direction)
{
	u8 Local_u8ErrorState = OK;
	u16 Local_u16Counter,Local_u16Revolution;


	Local_u16Revolution = Copy_u16Angle / (MOTOR_STEPPER_RESOLUTIUON*4);

	for(Local_u16Counter = 0; Local_u16Counter < Local_u16Revolution ;Local_u16Counter++)
	{
		MOTOR_u8StepperRotate(Copy_u8Direction);
	}

	return Local_u8ErrorState;

}
void MOTOR_voidStepperStop(void)
{
	DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_BLUE,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_PINK,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_YELLOW,DIO_u8PIN_HIGH);
	DIO_u8SetPinValue(MOTOR_STEPPER_PORT,MOTOR_STEPPER_ORANGE,DIO_u8PIN_HIGH);

}

void MOTOR_voidServoRotate(u8 Copy_u8Channel, u16 Copy_u16Degree)
{
	u16 Local_u16Maaped;

	/*Initialize Timer1 to Fast PWM*/
	TIMER1_u8Init(Copy_u8Channel, FAST_PWM ,DISCONNECT , TIMER_DIV_BY_8);

	/*Set ICR to 20ms seconds*/
	TIMER1_u8SetICR(20000);

	Local_u16Maaped = Mapping(0,360,150,1300,Copy_u16Degree);

	/*Set Compare match out*/
	TIMER1_u8SetChannelACompMatchVal(Local_u16Maaped);

}
